# Diccionario de Traducción
diccionario = {
    "Árbol" : "Akwi",
    "Oso bandera" : "Bari",
    "Perro" : "Chapa",
    "Peta" : "Dati",
    "Encima" : "Dyake",
    "Casa" : "Etare",
    "Tigre" : "Iba",
    "Pez" : "Jae",
    "Paraba" : "Kara",
    "Yuca" : "Kwawe",
    "Peinar" : "Lluya",
    "Jochi colorado" : "Mada",
    "Pacay" : "Naja",
    "quema quema" : "Ñuwiri",
    "Llorando" : "Paya",
    "Garza blanca" : "Rau",
    "Batan" : "Sasu",
    "Flor" : "Shasha",
    "DIAS DE LA SEMANA" : "WEKAKAKWANA SEMANAJUKE",
    "Domingo" : "Dumiku",
    "Lunes" : "Runeshi",
    "Martes" : "Marteshi",
    "Miércoles" : "Mirikureshi",
    "Jueves" : "Weweshi",
    "Viernes" : "Wiereneshi",
    "Sábado" : "Sawaru",
    "MESES DEL AÑO" : "MARAJUKE BADIKWANA",
    "Enero" : "Katibuti badi",
    "Febrero" : "Weberu badi",
    "Marzo" : "Marusu badi",
    "Abril" : "Abiri badi",
    "Mayo" : "Mayu badi",
    "Junio" : "Juñu badi",
    "Julio" : "Jullu badi",
    "Agosto" : "Agustu badi",
    "Septiembre" : "Setibe badi",
    "Octubre" : "Utupe badi",
    "Noviembre" : "Nubiere badi",
    "Diciembre" : "Disibe badi",
    "Buenos días" : "Bandia",
    "Buenas tardes" : "Bastare",
    "Buenas noches" : "Banuchi",
    "Buenos día papá" : "Bandia tata",
    "Buenas tardes mamá" : "Bastare mama",
    "Buenas noches abuelo" : "Banuchi babachi",
    "Buenas noches abuela" : "Banuchi anuchi",
    "Buenos días tío" : "Bandia tatiine",
    "Buenos días tía" : "Bandia nene",
    "Buenas tardes tío" : "Bastare kuku",
    "Buenas tardes tía" : "Bastare kwaine",
    "Buenas noches profesor" : "Banuchi ekabawityatike",
    "Buenos días estudiantes" : "Bandia kabawityatiyakwanake",
    "Estamos bien gracias" : "Jidadya ekwana Yusurupai",
    "Nosotros nos vamos" : "Kadujutiya ekwana",
    "PALABRAS MÁS USUALES" : "KISARATIKWANA DYAKE TSUMETANAYAKE",
    "Hola" : "Are",
    "Si" : "Jejee",
    "Estoy presente" : "Riyadya ike",
    "No ha venido" : "Jewa ama",
    "No hay" : "Aijama",
    "No está" : "Aijamarike",
    "Poco" : "Jamajari kwita",
    "Falta" : "Jamajari",
    "Ya va estar" : "Amena kwita",
    "Falta poco" : "Jamajari piji",
    "Listo" : "Amena",
    "No" : "Aama",
    "No hay" : "Aijama",
    "Muy bien" : "Jida kwita-+",
    "Mal" : "Jidama",
    "Regular" : "Jida Jida",
    "Así" : "Jadya",
    "No es así" : "Jadike ama",
    "PREGUNTAS Y RESPUESTAS" : "BAKADURAKWANA KEMITSA",
    "donde vas" : "Eju mi kwaya",
    "chaco" : "Teeju",
    "bañar" : "Nawira",
    "cazar" : "Babira",
    "pasear" : "Tarepera",
    "pescar" : "Wikamutyara",
    "Cuándo fuiste" : "Ejetupu mi cuaya",
    "hace rato" : "Wekaka",
    "Chancho asado" : "Kuchi ekwawike",
    "Qué comiste" : "Ai mi arawa",
    "Dónde dormiste" : "Eju mi tawiwa",
    "En la casa de mi tío" : "Tatiineja etareju",
    "Cuando te iras" : "Eje tupu mi diruya",
    "Mañana" : "Metajudya",
    "nombre de los animales" : "KWANUBI KWANAJA EBAKANI",
    "Anta" : "Awada",
    "Guaso" : "Dukweri",
    "Taitetú" : "Waburasa",
    "Chancho de tropa" : "Waburu",
    "Jochi pintado" : "Bakajume",
    "Jochi colorado" : "Mada",
    "Hurina" : "Yara pasa",
    "Leopardo" : "Dukweri iba",
    "Borochi" : "Borochi",
    "Gamo" : "Siwa",
    "Siervo" : "Pisini",
    "Tatú" : "Tsudi",
    "Tatú pampeño" : "Buru",
    "Peta" : "Dati",
    "Peta del agua" : "Ena Dat",
    "Tejón" : "Jukuri",
    "Mono silvador" : "Jiruwa",
    "Mono chichilo" : "Jawi",
    "Mono maneche" : "Duu",
    "Mono nocturno" : "Dide",
    "Mono lucachi" : "Dukwadukwa",
    "Ardilla" : "Dawapa",
    "Huichi" : "Ushu",
    "Caballo" : "Kawayu",
    "Oveja" : "Uwisha",
    "Gato" : "Mishi",
    "Perro" : "Chapa",
    "Gallina" : "Takure",
    "Pato" : "Juje",
    "Pajarito" : "Chai",
    "Angola" : "Epu Buñari",
    "nombre de los peces" : "JAE BAKANI KWANA",
    "Pintado" : "Chirije",
    "Pacú" : "Umija ebari",
    "Curvina" : "Sawana",
    "Benton" : "Sawa",
    "Yeyú" : "Dami",
    "Palometa" : "Make",
    "Yatorana" : "Mamure",
    "Tucunaré" : "Tsabuna",
    "Sábalo" : "Butsake",
    "Liza" : "Juta",
    "Raya" : "Ibabi",
    "Carancho" : "Siyu",
    "Simbao" : "Batsu",
    "NOMBRE DE LOS CEREALES" : "ARA ISHU KWANAJA EBAKANI KWANA",
    "Yuca" : "Kwawe",
    "Camote" : "Kunukaji",
    "Arroz" : "Arusu",
    "Maíz" : "Ijike",
    "Maní" : "kanise",
    "lima" : "rima",
    "naranja" : "narasa",
    "limón" : "rimu",
    "platano" : "budari",
    "guineo" : "kashi",
    "lúcumu" : "uja kaka",
    "utencilios de cocina" : "kusinaju tsumetanayakwanake",
    "plato" : "peja",
    "cuchara" : "emetuku adakike",
    "olla" : "emarikaka",
    "cuchillo" : "kuchiru kaka",
    "sarten" : "ekiniki baju bajuishuke",
    "caneco" : "jaru",
    "herramientas de trabajo" : "mere ishu tsumetanayakwanake",
    "pala" : "wakaba",
    "hacha" : "jacha",
    "machete" : "kuchiru",
    "picota" : "pikuta",
    "lampa" : "lampa",
    "nombres de los insectos": "KABAPETIYA KWANAJA EBAKANI KWANA",
    "mariposa" : "japipi",
    "grillo" : "ajari",
    "gusano" : "etsena",
    "mosquito" : "dii",
    "mosca" : "jeweweru",
    "coñera" : "murawawa",
    "marigui" : "tsani",
    "puguilla" : "rukwisha",
    "peto" : "bira",
    "hormiga" : "puki",
    "sepe" : "tepatsu",
    "mi mujer" : "ekwe ewane",
    "yo escribo" : "era weneya",
    "yo escribí" : "era wenewa",
    "estoy escribiendo" : "ike wene weneya",
    "bolsa" : "shitara",
    "pronombre" : "bakani isara",
    "singular" : "peadyake",
    "yo" : "ike",
    "tu" : "mike",
    "el" : "tuke",
    "tu como te llamas" : "mike ai bakani",
    "el como se llama" : "tuke ai bakani",
    "yo tengo" : "ekwe aniya",
    "el tiene" : "tuja aniya",
    "plural" : "umadake",
    "familia" : "ata",
    "abuelo" : "baba",
    "abuela" : "anu",
    "mamá" : "mama",
    "hijo" : "ebakwa",
    "hija" : "ebakujuna",
    "nuera" : "ebakwa jawane",
    "yierno" : "ebakujuna yawike",
    "nieto" : "utsekwa",
    "tío" : "tatiine",
    "tio" : "kuku",
    "tía" : "nene",
    "tia" : "kwaine",
    "primo" : "eatsewe bataya",
    "prima" : "eatsewe bataya",
    "hermano mayor" : "usi",
    "hermano menor" : "jau",
    "hermana mayor" : "nasi",
    "hermana menor" : "jana",
    "Hermano" : "nuu",
    "Sobrina" : "Yunekwake",
    "Sobrino" : "Yukwake",
    "los colores" : "bape bape kwanake",
    "verde" : "sawada",
    "pudeda" : "rojo",
    "negro" : "seweda",
    "guindo" : "kwajetsa",
    "morado" : "makupudibae",
    "amarillo" : "jawada",
    "café" : "seweu",
    "blanco" : "pajada",
    "Copia tu nombre de la tarjeta" : "Wenekwe mikwe ebakani kirikaju eweneke petatsu",
    "ASI SOY YO" : "JADYA IKE",
    "Mi nombre es" : "Mi nombre es",
    "Dibújate y pinta" : "Mike emeya katitsu pudekwe",
    "Soy una" : "Ike",
    "Niña" : "Ebakujunapiji",
    "Soy un" : "Ike",
    "niño" : "Ebakwapiji",
    "Escribe tus nombres y apellidos" : "Wenekwe mikwe ebakani ijawa bakani jadya",
    "Calca tu mano izquierda" : "Piyekwe mikwe emetuku jani ekeke",
    "Calca tu mano derecha" : "Piyekwe mikwe emetukujida ekeke",
    "COMPLETA EL DIBUJO" : "YUTANEKWE EMEYA EMEYA EAKE",
    "Mano" : "EMETUKUEWACHI",
    "Cara" : "EBUTSEKINI",
    "Pies" : "ewachi",
    "jabon" : "jabu",
    "agua" : "ena",
    "peine" : "yapere",
    "Dibuja un árbol:" : "Kweyakwe akwi",
    "árbol" : "Akwi",
    "Mono rubio" : "Aja",
    "Grillo" : "Ajari",
    "Abuela" : "Anu",
    "Busca en otro libro las palabras con A, a, a corta y lo prendes" : "Sarekwe peya kiririkaju A, a, a rakatsu sipitwe ",
    "hogar" : "etare",
    "casa" : "etare",
    "hay 3 clases de dibujos elige uno de ellos" : "Aniya tu kimisha emeya emeya eake mepekwe peadya E, e tsewekatibutiyake ebakani",
    "rasimo" : "Esa",
    "venteador" : "Epiki",
    "Cabo" : "Etsure",
    "Dibuja un tigre" : "Kweyakwe peadya iba",
    "dibuja" : "Kweyakwe",
    "pluma" : "ududu",
    "Bela" : "Ude",
    "sembrar" : "uwaya",
    "mordió" : "karuwa",
    "chulo" : "churu",
    "Mujer" : "Epuna",
    "Gente" : "Ekwita",
    "Niño" : "Ebakwapiji",
    "Joven" : "Deka ewe ebari",
    "Anciano" : "Deka esiri",
    "Edad" : "Eje uma Mara",
    "Amigo" : "Situ",
    "Vecino" : "Japadama aniyake",
    "Hombre sabi" : "Deka baweke",
    "Hombre" : "Deka",
    "Persona" : "Ekwita",
    "Niña" : "Ebakujunapiji",
    "Señorita" : "Epuna ewe ebari",
    "Anciana" : "Epuna esiri",
    "Enamorado" : "Ekwe kabijiseriti",
    "Novio" : "kakemitidadiyake",
    "Dueño" : "Emechiki",
    "Enemigo" : "Ujeuke",
    "Esposa" : "Ewane",
    "Madre" : "Mama ike susukike",
    "Abuela" : "Anu",
    "Yerno" : "Ebakujuna yawike",
    "Cuñado" : "Jakwi",
    "Hija" : "Ebakujuna",
    "Hija mayor" : "Ebakujuna Ikweneke",
    "Menor" : "Tupujuke",
    "Viuda" : "Awe emajuke",
    "Esposo" : "Eawe",
    "Padre" : "Tata ike bakike",
    "Hermano Menor" : "Jau",
    "Abuelo" : "Baba",
    "Nuera" : "Ebakwajawane",
    "Cuñada" : "Usijawane",
    "Hijo" : "Ebakwa",
    "ENFERMEDADES" : "UJEJEDAKE UJEJEDAMAKE",
    "Ciego" : "Shuwi",
    "Medicina" : "Esamaki",
    "Sordo" : "Isawe",
    "Herida" : "Etake",
    "Dolor" : "Uje",
    "Mudo" : "Kisarati",
    "Ampolla" : "Ekujuta",
    "Demente" : "Ekijawatike",
    "Tos" : "Uju",
    "Enfermedad" : "Ujeje",
    "Enfermarse" : "Ujejeda juya",
    "Enfermo" : "Ujejeda",
    "NOMBRE DE LAS ENFERMEDADES" : "UJEJEKWANAJA EBAKANI",
    "Diarrea" : "Buju",
    "Viruela" : "Ekwita uke",
    "Tuberculosis" : "Yarapesike ujeje",
    "Fiebre" : "Baara",
    "Paludismo" : "Tadada baara",
    "Cáncer" : "Ujeje majuishuke",
    "Mal de ojo" : "Yatuka ujeje",
    "Vómito" : "Kapushati",
    "Dolor de muela" : "Etse ujejera",
    "Dolor de oído" : "kani ujera",
    "Nausea" : "Pamemeya",
    "Resfrío" : "Badake",
    "Reumatismo" : "Badake ujeje",
    "Quemazón" : "Etiruke",
    "Picazón" : "Bijijitereya",
    "Enano" : "Barudama",
    "Jorobado" : "Ereme",
    "Grano de la piel" : "Tsuka tsuka",
    "Llaga" : "Ñajañaja",
    "Nacido" : "kwinanawa",
    "AVES" : "UPATIKWANA",
    "Cóndor" : "Jamani baba",
    "Gallo" : "Takure deka",
    "Gallina" : "Takure epuna",
    "Pollo" : "Takure ewe ebari",
    "Paloma" : "Wei",
    "Pato" : "Juje",
    "Perdí" : "Buni",
    "Tucán" : "Tsukwe",
    "Tucancillo" : "Rarasawa",
    "Carpintero" : "Mayawa",
    "Tojo" : "Wapa",
    "Seboí" : "Piyukuri",
    "Tordo" : "chico",
    "Sucha" : "Jamani",
    "Mutún" : "Witisi",
    "Huaracachi" : "Waraka",
    "Perdiz" : "Waparikwama",
    "Gaviota" : "Ena dirikike",
    "Aguila" : "Wiwipa",
    "Buho" : "Pupu",
    "Lechuza" : "Yura",
    "Pato cuerbo" : "Ena shukwi",
    "Tapacaré" : "Tsamiku",
    "Cigüeña" : "Shirite",
    "Loro" : "Kurakwa",
    "Ñandú" : "Uchani",
    "PECES" : "JAE KWANA",
    "PARTES DEL CUERPO" : "EKWITA",
    "Piel" : "Ebiti",
    "Carne" : "Erami",
    "Sangre" : "Ami",
    "Hueso" : "Etsau",
    "Cabello" : "Etsaru",
    "Cabeza" : "IyuKa",
    "Oreja" : "IjaKa",
    "Ojo" : "YatuKa",
    "Nariz" : "Ewikani",
    "Boca" : "Ekwatsa",
    "Diente": "Etse",
    "lengua" : "yana",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",
    "" : "",

}

import string

def limpiar_frase(frase):
    return frase.translate(str.maketrans('', '', string.punctuation))

def traducir(frase):
    frase = limpiar_frase(frase.lower())  # Limpia puntuación y pasa a minúsculas
    if frase in diccionario:
        return diccionario[frase]

    palabras = frase.split()
    traduccion = [diccionario.get(palabra, palabra) for palabra in palabras]
    return " ".join(traduccion)
def traducir(frase):
    frase = limpiar_frase(frase.lower())
    palabras = frase.split()
    traduccion = []
    for palabra in palabras:
        traduccion.append(diccionario.get(palabra, f"[{palabra}]"))  # Marca palabras no traducidas
    return " ".join(traduccion)


# Función para traducir frases
def traducir(frase):
    frase = frase.lower()
    # Verificar primero si la frase completa está en el diccionario
    if frase in diccionario:
        return diccionario[frase]
    
    palabras = frase.split()  # Divide en palabras
    traduccion = []
    for palabra in palabras:
        traduccion.append(diccionario.get(palabra, palabra))  # Traduce palabra o deja igual
    return " ".join(traduccion)


# Interacción con el usuario
if __name__ == "__main__":
    print("Bienvenido al traductor JIF de español a idioma originario Cavineño.")
    print("Escribe 'salir' para terminar.\n")
    while True:
        entrada = input("Escribe una frase en español: ")
        if entrada.lower() == "salir":
            print("¡Gracias por usar el traductor JIF! Hasta luego.")
            break
        print("Traducción:", traducir(entrada))
